### ISSUE TITLE
npm package not working in live server

### ISSUE THREAD

**Issue by sudarsan15** [bzarras/newsapi#12]
I have started a new express project I tested on the live server it worked then the first package I installed was news API package and I added API Key. it worked in localhost but when I put in the live server issue started.

The error is given below:

at require (internal/module.js:12:17)
at Object.<anonymous> (/var/www/html/demo/routes/index.js:4:17)
at Module._compile (module.js:410:26)
at Object.Module._extensions..js (module.js:417:10)
SyntaxError: Unexpected token ...
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:374:25)
at Object.Module._extensions..js (module.js:417:10)
at Module.load (module.js:344:32)
at Function.Module._load (module.js:301:12)
at Module.require (module.js:354:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/var/www/html/demo/routes/index.js:4:17)
at Module._compile (module.js:410:26)
at Object.Module._extensions..js (module.js:417:10)

**Comment by bzarras** [comment]
@sudarsan15 what version of Node are you running on your live server?

**Comment by sudarsan15** [comment]
my node version is : v8.9.1
